---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rodrigodr/home
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH