---
deployment:
  tasks:
    - export DEPLOYPATH=/home/torrshhb/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH